//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoldFever.GeneratedCode.Model;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Boat : MoveableObject
	{
		public int cargoLoad
		{
			get;
			private set;
		}

	    public Boat()
	    {
	        isFull = false;
	        cargoLoad = 0;
	    }

		public override void DoMove()
		{
		    if (this.Location.Next.CanMoveHere(this))
		    {
                if (!this.Location.CanLeaveHere()) return;
                if (this.Location.Next.DetectCollision()) return;
		        this.Location.MoveableObject = null;
		        this.Location = this.Location.Next;
		    }
		}

		public override void DistributeCargo()
		{
		    cargoLoad++;
		    if (cargoLoad == 8)
		    {
		        isFull = true;
		    }
		}

	    public override void Accept(IVisitor visitor)
	    {
	        visitor.Visit(this);
	    }
	}
}

