//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoldFever.GeneratedCode.Model;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cart : MoveableObject
	{
		public bool hasCollided
		{
			get;
			set;
		}

	    public Cart()
	    {
	        hasCollided = false;
	        isFull = true;
	    }

		public override void DoMove()
		{
		        if (this.Location.Next != null && !this.Location.Next.CanMoveHere(this)) return;
                if (!this.Location.CanLeaveHere()) return;
                if (this.Location.Next != null && this.Location.Next.DetectCollision()) 
		        {
		            hasCollided = true;
		            return;
		        }
		    this.Location.MoveableObject = null;
            this.Location = this.Location.Next;
		}

		public override void DistributeCargo()
		{
		    this.isFull = false;
		}

	    public override void Accept(IVisitor visitor)
	    {
	        visitor.Visit(this);
	    }
	}
}

