//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class CollectionManager
	{
		public abstract void MoveAllMoveableObjects();

		public abstract void CreateNewMoveableObjects();
	}
}

