//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoldFever.GeneratedCode.Model;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Dock : Track
	{
		public Track Docktrack
		{
			get;
			set;
		}

		public void FillBoat()
		{
            if (this.MoveableObject == null) return;
		    if (Docktrack.MoveableObject != null)
		    {
                this.MoveableObject.DistributeCargo();
                Docktrack.MoveableObject.DistributeCargo();
		    }
		}

	    public override bool CanLeaveHere()
	    {
	        return MoveableObject.isFull;
	    }

	    public override void Accept(IVisitor visitor)
	    {
            if (this.MoveableObject != null)
            {
                this.MoveableObject.Accept(visitor);
            }
            else
            {
                visitor.Visit(this);
            } 
	    }
	}
}

