//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoldFever.GeneratedCode.Model;

namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Track : IVisitable
	{
	    private Track _next;

	    public MoveableObject MoveableObject
		{
			get;
			set;
		}

	    public virtual Track Next
	    {
	        get { return _next; }
            set { if ((_next = value) != null) Next.Previous = this; }
	    }

	    public Track Previous
	    {
	        get; set;
        }

	    public bool IsVertical { get; set; }

        public bool IsCorner { get; set; }

        public virtual bool CanMoveHere(MoveableObject moveable)
        {
            return true;
        }

        public virtual bool DetectCollision()
	    {
	        return MoveableObject != null;
	    }

	    public virtual bool CanLeaveHere()
	    {
	        return true;
	    }

	    public virtual void Accept(IVisitor visitor)
	    {
	        if (this.MoveableObject != null)
	        {
	            this.MoveableObject.Accept(visitor);
	        }
	        else
	        {
                visitor.Visit(this); 
	        }  
	    }
	}
}

