//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GoldFever.GeneratedCode.Model;

namespace Proces
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class ViewController : IVisitor
	{

	    private string objectToRepresent;

		public ConsoleView ConsoleView
		{
			get;
			set;
		}

	    public GameController GameController
	    {
	        get; set;
        }

	    public ViewController()
	    {
	        ConsoleView = new ConsoleView();
	        objectToRepresent = "";
	    }
        
		public void showGame()
		{
			ConsoleView.showGame(this);
		}

	    public void Visit(Track visitee)
	    {
	        if (visitee.Next is IncomingSwitch)
	        {
	            IncomingSwitch myIncomingSwitch = (IncomingSwitch) visitee.Next;
                objectToRepresent = myIncomingSwitch.UpTrack.Equals(visitee) ? "═╗ " : "═╝ ";
	        }
	        else if (visitee.Previous is OutgoingSwitch)
	        {
                OutgoingSwitch myoOutgoingSwitch = (OutgoingSwitch)visitee.Previous;
                objectToRepresent = myoOutgoingSwitch.UpTrack.Equals(visitee) ? " ╔═" : " ╚═";
	        }
	        else
            {
	        if (visitee.IsCorner)
                {
                    objectToRepresent = "═╣ ";
                }
                else
                {
                    if (visitee.IsVertical)
                    {
                        objectToRepresent = " ║ ";
                    }
                    else
                    {
                        objectToRepresent = "═══";
                    }
                } 
	        }
	                
	    }

	    public void Visit(Boat visitee)
	    {
            objectToRepresent = "≤" + visitee.cargoLoad + "≥";
	    }

	    public void Visit(Cart visitee)
	    {
	        if (!visitee.isFull)
	        {
	            objectToRepresent = "<_>";
	        }
	        else
	        {
                objectToRepresent = "<◙>";
	        }    
	    }

	    public void Visit(OutgoingSwitch visitee)
	    {
	        if (!visitee.gateUp)
	        {
                objectToRepresent = "═╗" + visitee.Number;
	        }
	        else
	        {
                objectToRepresent = "═╝" + visitee.Number;
	        }
	    }

	    public void Visit(IncomingSwitch visitee)
	    {
            if (visitee.gateUp)
            {
                objectToRepresent = visitee.Number +"╚═";
            }
            else
            {
                objectToRepresent = visitee.Number + "╔═";
            }
	    }

	    public void Visit(NoCollisionTrack visitee)
	    {
            objectToRepresent = "╧══";
	    }

	    public void Visit(Warehouse<Boat> visitee)
	    {
            objectToRepresent = "|B|";
	    }

	    public void Visit(Warehouse<Cart> visitee)
	    {
            objectToRepresent = "|W|";
	    }

	    public void Visit(Dock visitee)
	    {
            objectToRepresent = "▒▒▒";
	    }

	    public string getStringForIVisitable(int y, int x)
	    {
	        IVisitable myVisitable = GameController.Game.getMap()[y, x];
	        if (myVisitable == null) return "   ";
	        myVisitable.Accept(this);
	        return objectToRepresent;
	    }

	    public string getStringForTimeAndScore()
	    {
	        string returnableString = "├COUNTDOWN: "+ GameController.GetTimer() +"┤ ├SCORE:" + GameController.Game.GameScore + "┤";
            return returnableString;
	    }

	    public void showEndScreen()
	    {
	        ConsoleView.showEndScreen(this);
	    }

	    public char getInput()
	    {
	        return ConsoleView.getInput();
	    }

	    public void showCountdownAndScore()
	    {
	        ConsoleView.ShowCountdownAndScore(getStringForTimeAndScore());
	    }

	    public void ShowTitleScreen()
	    {
            ConsoleView.ShowTitleScreen();
	    }

	    public void ShowComplete()
	    {
	        ConsoleView.ShowComplete(this, getStringForTimeAndScore());
	    }
	}
}

